### ISSUE TITLE
Latest release x64dbg will be crash

### ISSUE THREAD

**Issue by stonedreamforest** [0ffffffffh/Api-Break-for-x64dbg#4]

**Comment by stonedreamforest** [comment]
Api-Break-for-x64dbg：Beta release of 0.3.18

**Comment by stonedreamforest** [comment]
Whether there are shortcuts?

**Comment by 0ffffffffh** [comment]
Can you give me a bit detail about the crash? For example

Which platform are you running? 32 bit or 64 version?

What steps are caused or when is it happening? 

I can quickly diagnose and fix them if I get some detail about this issue.

Thanks for your feedback.

**Comment by stonedreamforest** [comment]
win7  64
![gif](https://cloud.githubusercontent.com/assets/16742566/22622889/e9e043aa-eb82-11e6-9796-906a044d4b64.gif)

**Comment by 0ffffffffh** [comment]
Before I start to inspect that issue there is something to needs to be clear.

Seems to your Api Break version older than 0.3.18. Because version 0.3.18 has "Settings" section on the plugin's menu. But yours dont have it as I saw.

![screenshot_56](https://cloud.githubusercontent.com/assets/437161/22623232/dad9425e-eb63-11e6-808a-c9da7793430b.png)
**Version 0.3.18**

Can you make sure that you are running the latest version? I may have already fixed. If the problem still occurs I will be working on as soon as possible to fix it.

**Comment by stonedreamforest** [comment]
i use 

![default](https://cloud.githubusercontent.com/assets/16742566/22631794/23857c12-ec4e-11e6-948a-a76548049d68.png)
