### ISSUE TITLE
Need msvcp140.dll on XP system

### ISSUE THREAD

**Issue by ttimasdf** [0ffffffffh/Api-Break-for-x64dbg#7]
x64dbg shipped with VC12 dlls which works on most systems OOB. However, this plugin introduced a new dependency which breaks support on old XP and 2003. Is there any reason of not using the same VC runtime?

**Comment by 0ffffffffh** [comment]
@ttimasdf that was a default toolset configuration. absolutely there is no reason to NOT use vc12.  that's why this project is currently in beta. Thanks a lot for the feedback. I fixed this issue on the beta-branch commit ref -> 0ffffffffh@ce07a58a3096cb2d4a651d720fdb05da4de250ce

I'll release a compiled binary as soon as possible.

**Comment by ttimasdf** [comment]
Thanks for the great work 👍
